apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ldugtpmwp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ldugtpmwp-java-springboot-gitops